### ISSUE TITLE
OCM ManifestWork labeler doesn't seem to be working: Error marshaling JSON

### ISSUE THREAD

**Issue by mikeshng** [clubanderson/hackathon-labeler#5]
I ran the README instruction `k apply -f examples/kubectl/pass --label=app.kubernetes.io/part-of=sample --context=kind-kind --namespace=temp --overwrite --l-mw-create`

I was expecting an output but I got the following:

```
deployment.apps/my-app-deployment2 created
service/my-app-service2 created

labeler plugin: "PluginLabeler":

  🏷️ labeled object /v1/namespaces "temp" in namespace "" with app.kubernetes.io/part-of=sample
  🏷️ labeled object apps/v1/deployments "my-app-deployment2" in namespace "temp" with app.kubernetes.io/part-of=sample
  🏷️ labeled object /v1/services "my-app-service2" in namespace "temp" with app.kubernetes.io/part-of=sample


labeler plugin: "PluginCreateMW":

  🚀 Attempting to create ManifestWork object "change-me" in namespace "temp"
Error marshaling JSON: json: unsupported type: map[interface {}]interface {}
```

Another side note is `temp` namespace is usually not available. How about using "default" as the example namespace? That is more widely available.

**Comment by clubanderson** [comment]
yes - I know of this issue - I think it happens when the manifestwork CRD is not installed in the context/cluster you are aiming at. Can you tell me if 'temp' namespace and manifestwork exist in the cluster you are attempting to apply to?

**Comment by clubanderson** [comment]
actually, this might be before apply - I am investigating

**Comment by clubanderson** [comment]
I think this is now fixed in 0.18.2. I do not have OCM here to test with yet. If you can please test with a cluster that has manifestworks to see if applies properly.

**Comment by clubanderson** [comment]
0.18.5 should fix your issue

**Comment by clubanderson** [comment]
closing issue - working properly per @mikeshng
